### ISSUE TITLE
Possible Feature

### ISSUE THREAD

**Issue by lwhiteley** [jrcryer/grunt-pagespeed#18]
[Could be MileStone]

Would be nice to generate a Html report of all the paths tested where each path tested would have their own detailed view.

**_UI Logic**_

> **As a consumer,**
>  **I Should**  be able to see a list of all paths tested 
>  **AND** be able to click on each to see a detailed view
> **So That** I could see or archive artifacts related to pagespeed testing

I am interested in hearing what folks think. If this is
- feasible
- a good idea

**Comment by geoffdavis92** [comment]
Any word/update on this? It's possible to output reports using the PSI CLI in the following fashion:

`$ psi https://domain.com/page --strategy desktop --format json > page-report.json`
