### ISSUE TITLE
How to run in an AngularJS Mobile Application?

### ISSUE THREAD

**Issue by FJLopezGarcia** [jrcryer/grunt-pagespeed#24]
I have an IONIC application and I would like to run pagespeed on it.
I am using ngrok to run pagespeed from localhost

``` javascript
    grunt.registerTask('psi-ngrok', 'Run pagespeed with ngrok', function () {
        var done = this.async();
        var port = 8100;

        ngrok.connect(port, function (err, url) {
            if (err !== null) {
                grunt.fail.fatal(err);
                return done();
            }
            grunt.config.set('pagespeed.options.url', url);
            grunt.task.run('pagespeed');
            done();
        });
    });
```

The following one is the grunt file section to manage pagespeed: I would like to analyze: 
http://localhost:8100/#/app/playlists
http://localhost:8100/#/app/search

``` javascript
        pagespeed: {
            options: {
                nokey: true,
                locale: "en_GB",
                threshold: 10
            },
            mobile: {
                options: {
                    strategy: "mobile",
                    locale: "en_GB"
                }
            },
            paths: {
                options: {
                    paths: [
                        "/#/app/playlists",
                        "/#/app/search"
                    ],
                    locale: "en_GB",
                    strategy: "mobile",
                    threshold: 10
                }
            }
        },
```

And here you can see the output, as you can see the results are the same for each page.. something is wrong. Do you know how to do it?
## Running "pagespeed:mobile" (pagespeed) task

URL:       6934024b.ngrok.com
Strategy:  mobile
Score:     71
CSS size                                   | 224.31 kB
HTML size                                  | 2.35 kB
JavaScript size                            | 110.81 kB
CSS resources                              | 2
Hosts                                      | 1
JS resources                               | 4
Resources                                  | 7
Static resources                           | 1
Total size                                 | 375 B
Enable GZIP compression                    | 27.21
Leverage browser caching                   | 0.75
Main resource server response time         | 9.31
Minify CSS                                 | 3.76
Minify JavaScript                          | 0.23

---

URL:       6934024b.ngrok.com
Strategy:  mobile
Score:     75
CSS size                                   | 224.31 kB
HTML size                                  | 2.35 kB
JavaScript size                            | 110.81 kB
CSS resources                              | 2
Hosts                                      | 1
JS resources                               | 4
Resources                                  | 7
Static resources                           | 1
Total size                                 | 375 B
Enable GZIP compression                    | 27.21
Leverage browser caching                   | 0.75
Minify CSS                                 | 3.76
Minify JavaScript                          | 0.23

---

URL:       6934024b.ngrok.com
Strategy:  mobile
Score:     75
CSS size                                   | 224.31 kB
HTML size                                  | 2.35 kB
JavaScript size                            | 110.81 kB
CSS resources                              | 2
Hosts                                      | 1
JS resources                               | 4
Resources                                  | 7
Static resources                           | 1
Total size                                 | 375 B
Enable GZIP compression                    | 27.21
Leverage browser caching                   | 0.75
Minify CSS                                 | 3.76
Minify JavaScript                          | 0.23

**Comment by jrcryer** [comment]
Hi @FJLopezGarcia,

Not knowing how your pages hang together, it is pretty difficult to say why you are getting these results.  I assume the framework loads and then uses AngularJS router to load the appropriate content.  The results from PSI would be similar as the initial page response (e.g. assets in the page) would be the same.

What are you trying to measure? Page load or initial render timings?

Ta, James
