### ISSUE TITLE
Don't continue process after pagespeed task

### ISSUE THREAD

**Issue by konstantin24121** [jrcryer/grunt-pagespeed#26]
Stoped after print results. Any Ideas?

**Comment by konstantin24121** [comment]
grunt 0.4.5 , Windows 8.1

**Comment by konstantin24121** [comment]
Don't work multitask, stoped after print first results

**Comment by mkilpatrick** [comment]
I'm also using grunt 0.4.5 and after the first process ends (either 1 or multiple paths), the process just hangs. It never completes to get to the next process if there is one, and it never completes if there is only one process.

**Comment by mkilpatrick** [comment]
It looks like the current count wasn't properly incrementing upon errors so the process would never complete. I've submitted a PR to fix it. https://github.com/jrcryer/grunt-pagespeed/pull/27

**Comment by muratozgul** [comment]
+1

**Comment by leptest** [comment]
+1

**Comment by paulradzkov** [comment]
Same problem (grunt 1.0.1, node v5.11.0)
