### ISSUE TITLE
Facing issue with google page insights

### ISSUE THREAD

**Issue by ahkhan696** [jrcryer/grunt-pagespeed#32]
hi,
I have facing issue when i search my domain for page insights. it showing question mark in result. please look the attachment.
thanks
![Screenshot_5](https://user-images.githubusercontent.com/16847283/67738062-230d6c80-fa2f-11e9-928c-b48978d48a4a.png)

**Comment by jrcryer** [comment]
Hi ahkhan696,

This repo does not support the Google PageSpeed Insight site, this is maintained by Google.

Thanks,

James
